  
---
- hosts: lmsweb
  become: yes
  become_method: sudo
  tasks:

  - name: Install pip
    apt:
      update_cache: yes
      name: python3-pip

  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: install docker-py
    pip: name=docker-py

  - name: enable Docker services
    service:
      name: "docker"
      state: started
      enabled: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

  - name: Start nginx
    service:
      name: nginx
      state: started

  - name: Enable nginx
    service:
      name: nginx
      enabled: yes

  - name: import repositary
    shell: git clone -b terraform https://muralialakuntla3-admin@bitbucket.org/muralialakuntla3/lms-app.git
  
  - name: Check if container is running
    shell: docker ps

  - name: build docker image
    shell: cd lms-app/webapp/
    shell: docker build -t muralialakuntla3/web .

  - name: run docker container
    shell: docker run -dt --name web -p 80:80 muralialakuntla3/web

  - name: show running images
    shell: docker images
...