apiVersion: v1
kind: Service
metadata:
  name: lms-be-service
spec:
  type: LoadBalancer        # This is for  k8s cluster for minikube use NodePort service
  ports:
  - port: 3000
  selector:
    app: lms-be
