apiVersion: v1
kind: Service
metadata:
  name: dns-lb
spec:
  type: LoadBalancer     
  selector:
    component: frontend
  clusterIP: 10.100.197.145
  ports:
  - name: frontend # name is not required for single-port Services
    port: 80
