apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api 
    spec:
      containers:
      - name: api
        image: muralialakuntla3/api2
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: MODE
            value: production
