version: 0.2
phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - cd webapp
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
   #   - cd webapp
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - webapp/appspec.yml
    - webapp/scripts/**/*
    - webapp/dist/**/*
