version: 0.2
phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - cd api
      - chmod +x ./scripts/setup_postgresql.sh  # Ensure the script is executable
      - ./scripts/setup_postgresql.sh  # Execute the shell script for PostgreSQL setup
      - npm install
     # - sudo npm install pm2 -g
     # - sudo npx prisma db push
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
     # - NODE_PORT=3000 pm2 start -i 0 build/src/index.js
  post_build:
    commands:
      - echo Build completed on `date`
      - sudo cp package.json build/
    application_start:
      commands:
        - chmod +x ./scripts/app_start.sh  # Ensure the script is executable
        - ./scripts/app_start.sh  # Execute the app_start.sh script
      
# Include only the files required for your application to run.
artifacts:
  files:
    - api/appspec.yml
    - api/scripts/**/*
    - api/build/**/*
# environment variables
environment:
  variables:
    PG_HOST: localhost  # Since the database is on the same server
    PG_USER: postgres
    PG_PASSWORD: password
    PG_DATABASE: lmsdb
    BACKEND_PORT: 3000  # Specify your backend port here
    NODE_ENV: production
